const express = require("express");
const {registerValidations,loginValidations, } = require("../validations/userValidations");
const {register, login, registerCustomer, loginCustomer, getAdmin, deleteAdmin, getCustomer, deleteCustomer} = require("../controllers/usersController");
const router = express.Router();
router.post("/register",registerValidations, register);
router.get("/getAdmin/:page", getAdmin);
router.get("/get-customer/:page", getCustomer);
router.delete("/delete-customer/:id",deleteCustomer);
router.delete("/delete-admin/:id",deleteAdmin);
router.post("/CustomerRegister",registerValidations, registerCustomer);
router.post('/login',loginValidations, login);
router.post('/customerLogin',loginValidations, loginCustomer);
module.exports = router;